apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  labels:
    app: webserver-deploy
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30001
  selector:
    app: webserver-deploy
  type: NodePort

